- name: bootstrap the server
  hosts: local
  become: yes
  roles:
    - role: bootstrap

- name: install and configure wireguard
  hosts: local
  become: yes
  gather_facts: true
  roles:
    - role: wireguard
